"""Generate every pixel SVG in assets/ plus README.md from tools/profile.toml.

    python3 tools/build.py            # needs Python 3.11+, standard library only

Each component is written twice (-light / -dark); README.md switches between
them with <picture> + prefers-color-scheme, so the hero is a day scene in
light mode and a night scene in dark mode.
"""

import sys
import tomllib
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import cards  # noqa: E402
from scene import hero  # noqa: E402
from theme import THEMES  # noqa: E402

ROOT = HERE.parent
ASSETS = ROOT / "assets"
RAW = "https://raw.githubusercontent.com/{user}/{user}/output"


def load():
    with open(HERE / "profile.toml", "rb") as f:
        return tomllib.load(f)


def esc(s):
    return s.replace("&", "&amp;").replace('"', "&quot;").replace("<", "&lt;").replace(">", "&gt;")


THEME = "dark"   # set from profile.toml [player] theme: "dark" | "light" | "auto"


def pic(name, alt, width="100%", extra="", base="assets"):
    size = f' width="{width}"' if width else ""
    img = f'<img src="{base}/{name}-{{}}.svg"{size} alt="{esc(alt)}"{extra}>'
    if THEME in ("dark", "light"):
        return img.format(THEME)
    return (
        f'<picture><source media="(prefers-color-scheme: dark)" srcset="{base}/{name}-dark.svg">'
        + img.format("light") + "</picture>"
    )


def build_assets(prof):
    ASSETS.mkdir(exist_ok=True)
    abil_color = {a["code"]: a["color"] for a in prof["ability"]}
    quests = prof["quest"]
    n_main = sum(q["kind"] == "main" for q in quests)
    out = {}
    for th in THEMES:
        t = th["name"]
        out[f"hero-{t}"] = hero(th, prof)
        out[f"dialog-{t}"] = cards.dialog(th, prof)
        out[f"status-{t}"] = cards.status(th, prof)
        out[f"quests-{t}"] = cards.header(th, "QUEST LOG", "任务日志",
                                          f"{n_main} ACTIVE  {len(quests) - n_main} CLEARED", "coral")
        for i, q in enumerate(quests, 1):
            out[f"quest-{q['repo']}-{t}"] = cards.quest(th, q, i, abil_color)
        out[f"inventory-{t}"] = cards.inventory(th, prof)
        out[f"achievements-{t}"] = cards.achievements(th, prof)
        out[f"savedata-{t}"] = cards.header(th, "SAVE DATA", "存档", "AUTO-SAVED DAILY", "blue")
        out[f"footer-{t}"] = cards.footer(th, prof)
        out[f"btn-mail-{t}"] = cards.button(th, "SEND MAIL", "发邮件", "mail", "pink")
        out[f"btn-repos-{t}"] = cards.button(th, "ALL REPOS", "全部仓库", "chest", "peach")
    wanted = set()
    for name, svg in out.items():
        path = ASSETS / f"{name}.svg"
        wanted.add(path.name)
        path.write_text(svg, encoding="utf-8")
    for old in ASSETS.glob("quest-*.svg"):
        if old.name not in wanted:
            old.unlink()
    return out


def readme(prof):
    pl = prof["player"]
    user = pl["github"]
    gh = f"https://github.com/{user}"
    raw = RAW.format(user=user)
    lines = [
        "<!--",
        "  本文件由 tools/build.py 生成：改 tools/profile.toml 后运行 python3 tools/build.py。",
        "  Generated by tools/build.py from tools/profile.toml. Edit that file and re-run.",
        "-->",
        "",
        '<div align="center">',
        "",
        pic("hero", f"{pl['name'].title()} — AI-native builder · {pl['school']} · Nanjing"),
        "",
        pic("dialog", " ".join(prof["dialog"]["lines"]) + " " + prof["dialog"]["seeking"]),
        "",
        pic("status", "Abilities: " + "; ".join(
            f"{a['name']} ({a['code']}) Lv.{a['level']} — {a['keywords']}" for a in prof["ability"])),
        "",
        pic("quests", "Quest log"),
        "",
    ]
    quests = prof["quest"]
    for kind in ("main", "side"):
        row = []
        for q in (q for q in quests if q["kind"] == kind):
            alt = f"{q['repo']} — {q['zh']}: {q['desc']}"
            row.append(f'<a href="{gh}/{q["repo"]}">'
                       + pic(f"quest-{q['repo']}", alt, width="49%", extra=f' title="{esc(alt)}"') + "</a>")
        lines += ["\n".join(row), ""]
    more = prof.get("more", [])
    if more:
        lines += [
            "</div>",
            "",
            "<details>",
            f"<summary><b>更多支线任务 · More side quests ({len(more)})</b></summary>",
            "<br/>",
            "",
        ]
        lines += [f"- [**{m['repo']}**]({gh}/{m['repo']}) — {m['desc']}" for m in more]
        lines += ["", "</details>", "", '<div align="center">', ""]
    lines += [
        pic("inventory", "Tech stack: " + "; ".join(
            f"{c['name']}: " + ", ".join(i.rstrip('*') for i in c["items"]) for c in prof["inventory"])),
        "",
        pic("achievements", "Achievements: " + "; ".join(
            f"{a['title']} ({a['sub']})" for a in prof["achievement"])),
        "",
        pic("savedata", "Save data"),
        "",
        pic("save-data", "GitHub stats, refreshed daily", base=raw),
        "",
        pic("snake-pixel", "Contribution snake", base=raw),
        "",
        pic("footer", "Thanks for playing"),
        "",
        f'<a href="mailto:{pl["email"]}">' + pic("btn-mail", f"Email {pl['email']}", width=None,
                                                   extra=' height="48"') + "</a>",
        f'<a href="{gh}?tab=repositories">' + pic("btn-repos", "All repositories", width=None,
                                                   extra=' height="48"') + "</a>",
        "",
        f'<sub><a href="mailto:{pl["email"]}">{pl["email"]}</a> · 南京 Nanjing · '
        f'<img src="https://komarev.com/ghpvc/?username={user}&label=VISITORS&color=8D7AAE&style=flat-square" '
        'alt="profile views" align="center"></sub>',
        "",
        "</div>",
        "",
    ]
    (ROOT / "README.md").write_text("\n".join(lines), encoding="utf-8")


def main():
    global THEME
    prof = load()
    THEME = prof["player"].get("theme", "dark")
    out = build_assets(prof)
    readme(prof)
    size = sum(len(s.encode()) for s in out.values())
    print(f"wrote {len(out)} svgs ({size / 1024:.0f} KB) and README.md")


if __name__ == "__main__":
    main()
